repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6 # Use a recent, stable version
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0 # Use a recent, stable version
    hooks:
    -   id: mypy
        args: [--strict]
        additional_dependencies: [
            "pydantic>=2.0",
            "pydantic-settings",
            "types-requests",
            "typer",
            "lxml"
        ]
